# Generated by Django 6.0.3 on 2026-04-06 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('hash_adn_hardware', models.CharField(max_length=255, unique=True)),
                ('hash_imei', models.CharField(max_length=255, unique=True)),
                ('marca_modelo', models.CharField(max_length=255)),
                ('url_imagen_referencia', models.TextField(blank=True, null=True)),
                ('fecha_registro_blockchain', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
