# Generated by Django 6.0.3 on 2026-06-14 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'LIBRE'), ('ROBADO', 'ROBADO')], default='LIBRE', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialEscaneo',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_filtro', models.CharField(choices=[('IMEI', 'IMEI'), ('QR', 'QR')], max_length=20)),
                ('valor_consultado', models.CharField(max_length=255)),
                ('resultado_estado', models.CharField(choices=[('LIBRE', 'LIBRE'), ('ROBADO', 'ROBADO'), ('NO_REGISTRADO', 'NO_REGISTRADO')], max_length=20)),
                ('marca_modelo_detectado', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_escaneos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
