# Generated by Django 6.0.3 on 2026-06-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_dispositivo_estado_historialescaneo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='url_imagen_referencia',
            field=models.ImageField(blank=True, null=True, upload_to='devices/'),
        ),
    ]
