# Generated by Django 6.0.3 on 2026-06-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_dispositivo_url_imagen_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'LIBRE'), ('ROBADO', 'ROBADO'), ('EXTRAVIADO', 'EXTRAVIADO')], default='LIBRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialescaneo',
            name='resultado_estado',
            field=models.CharField(choices=[('LIBRE', 'LIBRE'), ('ROBADO', 'ROBADO'), ('EXTRAVIADO', 'EXTRAVIADO'), ('NO_REGISTRADO', 'NO_REGISTRADO')], max_length=20),
        ),
    ]
