# Generated by Django 6.0.3 on 2026-06-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_dispositivo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='hash_visual',
            field=models.CharField(blank=True, help_text='Identificador hash visual único basado en características', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='vector_caracteristicas',
            field=models.TextField(blank=True, help_text='Representación JSON del vector de 1280 floats extraído por EfficientNet', null=True),
        ),
    ]
