# Generated by Django 6.0.3 on 2026-06-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_dispositivo_hash_visual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTrazabilidad',
            fields=[
                ('id_trazabilidad', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('id_celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidad', to='devices.dispositivo')),
            ],
            options={
                'db_table': 'historial_trazabilidad',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
