# Generated by Django 6.0.3 on 2026-06-24 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_historialtrazabilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SolicitudTransferencia',
            fields=[
                ('id_transferencia', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ACEPTADA', 'ACEPTADA'), ('RECHAZADA', 'RECHAZADA')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='devices.dispositivo')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitud_transferencia',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
