# Generated by Django 6.0.3 on 2026-04-10 14:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=180)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('cuota_mensual', models.PositiveIntegerField(default=1000)),
                ('solicitudes_usadas', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marketplace API Key',
                'verbose_name_plural': 'Marketplace API Keys',
                'ordering': ['nombre_organizacion'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=180, unique=True)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('limite_solicitudes_mensual', models.PositiveIntegerField(default=1000)),
                ('solicitudes_realizadas_mes_actual', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_reseteo_solicitudes', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'verbose_name': 'Marketplace Client',
                'verbose_name_plural': 'Marketplace Clients',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_price_id', models.CharField(max_length=120, unique=True)),
                ('max_dispositivos', models.PositiveIntegerField(default=1)),
                ('tiene_verificacion_vision', models.BooleanField(default=False)),
                ('tiene_registro_blockchain', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dispositivo_id', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Log',
                'verbose_name_plural': 'Usage Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='saas.subscriptionplan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
