# Generated by Django 6.0.3 on 2026-04-10 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('limite_verificaciones_mensual', models.IntegerField(default=5)),
                ('verificaciones_usadas_este_mes', models.IntegerField(default=0)),
                ('fecha_ultimo_reseteo_verificaciones', models.DateField(default=django.utils.timezone.localdate)),
                ('plan_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='saas.subscriptionplan')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['usuario__correo_electronico'],
            },
        ),
    ]
